updated query support doc
readysettech/docs-old pull request #19
Opened 2022-10-14 01:49 UTC by celinebrass

2022-10-14 15:50 UTC, nickelization commented on docs/reference/query-support.md
> +  - ReadySet support enums in MySql but not Postgres
nit: MySQL (vs MySql). Also, typo of "support" vs "supports"

2022-10-14 15:50 UTC, nickelization commented on docs/reference/query-support.md
> +  - `greatest`
We also support `least` as well as `greatest`

2022-10-14 15:50 UTC, nickelization commented on docs/reference/query-support.md
> +- `CITEXT`
Besides adding `ENUM` and `CITEXT` we may want to mention that we support array types now too (it's mentioned above that we support array literals, but there's nothing here about it being a supported type).

2022-10-14 15:50 UTC, nickelization commented on docs/reference/query-support.md
> +- `CITEXT`
(Although I'm a little fuzzy on the specific features/limitations we have in our array support -- I'm just going off of the fact that I know we support at least some array functionality.)

2022-10-14 15:50 UTC, nickelization commented on docs/reference/query-support.md
> +  - String literals, quoted according to the SQL dialect being used (single quotes for postgresql, double or single quotes for mysql)
nit: as long as we're fixing up the formatting we may also want to change mysql to MySQL too

2022-10-14 15:50 UTC, nickelization commented on docs/reference/query-support.md
> +  - boolean literals `TRUE` and `FALSE`
Another nit, I know it was like this already and you just fixed the indentation, but as long as we're touching these lines, it feels a little sloppy that these three bullet points are not capitalized

2022-10-14 17:40 UTC, celinebrass commented on docs/reference/query-support.md
> +- `CITEXT`
Yeah I also wasn't clear on it -- i actually have a list of a few things I would like Griffin to add when he comes back. I will add this to it.

2022-10-14 17:52 UTC, jseldess requested changes

2022-10-14 17:52 UTC, jseldess commented on docs/reference/query-support.md
> +  - ReadySet does not support scalar subqueries in the `SELECT` clause
This bullet is no longer a sub-bulled of the one before. We need to revert to the previous indentation. 

You can check this in the preview build: https://docs-git-cb-update-query-support-readyset.vercel.app/reference/query-support/

2022-10-14 17:52 UTC, jseldess commented on docs/reference/query-support.md
> +  - The `WHERE` clause must have a single condition [expression](#expressions)
This bullet is no longer a sub-bulled of the one before. We need to revert to the previous indentation. 

You can check this in the preview build: https://docs-git-cb-update-query-support-readyset.vercel.app/reference/query-support/

2022-10-14 17:52 UTC, jseldess commented on docs/reference/query-support.md
> +  - ReadySet does not support expressions or field positions in the `GROUP BY` clause
This bullet is no longer a sub-bulled of the one before. We need to revert to the previous indentation. 

You can check this in the preview build: https://docs-git-cb-update-query-support-readyset.vercel.app/reference/query-support/

2022-10-14 17:52 UTC, jseldess commented on docs/reference/query-support.md
> +  - String literals, quoted according to the SQL dialect being used (single quotes for PostgreSQL, double or single quotes for MySQL)
Same as above. We need to revert to the previous indentation.

Same comment applied to various nested lists below as well. We should check throughout.

2022-10-17 14:38 UTC, jseldess approved these changes
LGTM! Thank you, @celinebrass! 

I know there are other updates still to add, but I'd like to get this PR merged and we can open follow-ups.

2022-10-17 14:43 UTC, merged