Update SQL Support and related docs
readysettech/docs-old pull request #30
Opened 2022-10-27 21:24 UTC by jseldess

- Restructure SQL support page to focus on 3 areas of support: replicating tables, caching queries, and custom SQL commands.
- Reformat certain sections as tables (data types, schema changes).
- Add ARRAY support to the data types section.
- Add a section on write support.
- Rename a few other sections and reduce some section nesting.
- Start improving the Cache Queries page.

This is just a start. Much work is still needed on both SQL Support ad Cache Queries.

Fixes https://readysettech.atlassian.net/browse/DOC-41 Fixes https://readysettech.atlassian.net/browse/DOC-38 Fixes https://readysettech.atlassian.net/browse/DOC-46

2022-10-27 21:39 UTC, glittershark requested changes

2022-10-27 21:39 UTC, glittershark commented on docs/guides/cache-queries.md
> +CREATE CACHE <name> FROM <query>;
```suggestion
CREATE CACHE [<name>] FROM <query>;
```

we can still explicitly spell out that it's optional, but this is a nice convention that I've seen for marking something as optional

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +    ReadySet takes an initial snapshot of tables from the upstream SQL database and then uses the database's replication stream to keep the snapshot accurate as the upstream tables are updated. To su
nit: hard-wrapping markdown files (eg to 80 chars) makes them a lot easier to read + review diffs of them, plus makes the diffs usually cover fewer lines and cause fewer merge conflicts

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +| `UUID` | ReadySet represents this type internally as a normalized string. This can cause different behavior than in MySQL or Postgres with respect to expressions or sorting. |
maybe it's worth linking to the postgres/mysql docs for these?

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +| `CITEXT` |
think this row is missing the (empty) second column

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +| `BYTEARRAY` |
think this row is missing the (empty) second column

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +| `DECIMAL`, `NUMERIC` |
this too

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +| `FLOAT`, `DOUBLE`, `REAL` |
and here

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +| `SERIAL`, `BIGSERIAL` |
and these two

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +ReadySet supports the UTF-8 character set for strings and always compares strings case-sensitively and sorts strings lexicographically. ReadySet does not support any other character sets, alternative
we probably want to say something about citext here

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +ReadySet updates its snapshot and any releated cached query results when it receives the following schema changes via the database's replication stream:
this is not quite true - all alter and drop table requests *I believe* currently drop all related cached queries, and don't automatically recreate them - @frannoriega can check me on that

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +    - `EXISTS` without a subquery
We support `EXISTS` with a subquery (I'm not sure we ever supported it *without* one, this may have originally just been a typo), and that subquery can be correlated

2022-10-27 21:39 UTC, glittershark commented on docs/reference/sql-support.md
> +- `EXISTS` with a subquery
we support this now (see above)

2022-10-28 13:54 UTC, jseldess commented on docs/reference/sql-support.md
> +| `UUID` | ReadySet represents this type internally as a normalized string. This can cause different behavior than in MySQL or Postgres with respect to expressions or sorting. |
I like that idea. Want to discuss an extension of it when we meet.

2022-10-28 13:54 UTC, jseldess commented on docs/reference/sql-support.md
> +    ReadySet takes an initial snapshot of tables from the upstream SQL database and then uses the database's replication stream to keep the snapshot accurate as the upstream tables are updated. To su
OK. I'll work on this.

2022-10-28 13:57 UTC, jseldess commented on docs/reference/sql-support.md
> +| `CITEXT` |
Done.

2022-10-28 13:57 UTC, jseldess commented on docs/reference/sql-support.md
> +| `BYTEARRAY` |
Done.

2022-10-28 13:57 UTC, jseldess commented on docs/reference/sql-support.md
> +| `DECIMAL`, `NUMERIC` |
Done.

2022-10-28 13:57 UTC, jseldess commented on docs/reference/sql-support.md
> +| `FLOAT`, `DOUBLE`, `REAL` |
Done.

2022-10-28 13:57 UTC, jseldess commented on docs/reference/sql-support.md
> +| `SERIAL`, `BIGSERIAL` |
Done.

2022-10-28 16:26 UTC, greg-mckeon commented on docs/reference/sql-support.md
> +ReadySet updates its snapshot and any releated cached query results when it receives the following schema changes via the database's replication stream:
could we auto-create them?

2022-10-31 19:41 UTC, jseldess commented on docs/reference/sql-support.md
> +| `UUID` | ReadySet represents this type internally as a normalized string. This can cause different behavior than in MySQL or Postgres with respect to expressions or sorting. |
Refactor the data type section. Linking to the specific mysql and postgres docs per data type.

2022-10-31 19:41 UTC, jseldess commented on docs/guides/cache-queries.md
> +CREATE CACHE <name> FROM <query>;
Done.

2022-10-31 19:42 UTC, jseldess commented on docs/reference/sql-support.md
> +    - `EXISTS` without a subquery
Done.

2022-10-31 19:42 UTC, jseldess commented on docs/reference/sql-support.md
> +- `EXISTS` with a subquery
Done.

2022-10-31 20:00 UTC, frannoriega commented on docs/reference/sql-support.md
> +ReadySet updates its snapshot and any releated cached query results when it receives the following schema changes via the database's replication stream:
We drop all of them and don't recreate.
I'm thinking that we could implement auto-creation, if we can make the query removal logic return the queries that were removed, and _attempting_ to add them again.
There are two corner cases to consider:
- How to handle queries that fail to reinstall, skipping the ones that fail (think of queries that select a column that doesn't exist anymore). I'm guessing we could just skip those, but I wanted to bring it up.
- The case of `SELECT *` queries. If columns were dropped/added, those queries would be recreated but will not yield the same results as before. We should _at least_ warn users in that case.

2022-11-01 15:22 UTC, jseldess commented on docs/reference/sql-support.md
> +ReadySet updates its snapshot and any releated cached query results when it receives the following schema changes via the database's replication stream:
Thanks, @frannoriega. Update the language.

2022-11-01 15:28 UTC, jseldess commented on docs/reference/sql-support.md
> +    ReadySet takes an initial snapshot of tables from the upstream SQL database and then uses the database's replication stream to keep the snapshot accurate as the upstream tables are updated. To su
Will work on this in a follow-up. It's easy to configure my editor to soft-wrap. I'm having trouble configuring it to hard-wrap.

2022-11-01 15:38 UTC, jseldess commented on docs/reference/sql-support.md
> +ReadySet supports the UTF-8 character set for strings and always compares strings case-sensitively and sorts strings lexicographically. ReadySet does not support any other character sets, alternative
Done.

2022-11-01 15:43 UTC, merged

2022-11-01 15:45 UTC, greg-mckeon commented on docs/reference/sql-support.md
> +ReadySet updates its snapshot and any releated cached query results when it receives the following schema changes via the database's replication stream:
this isn't the right spot for this, but I don't think we need to warn. Our job is to mirror the upstream, so if the upstream changes, we're expected to change as well.

2022-11-01 17:20 UTC, jseldess commented on docs/reference/sql-support.md
> +ReadySet updates its snapshot and any releated cached query results when it receives the following schema changes via the database's replication stream:
@greg-mckeon, I don't understand. Are you saying we shouldn't advise users to re-cache the queries after a snapshot?