Document readyset commands
readysettech/docs-old pull request #85
Opened 2023-01-27 22:33 UTC by jseldess

- Add cli sections with overview and command-specific pages
- Document all relevant options
- Provide basic examples

Next: Add tutorial for deployment with binaries

Addresses: DOC-17 and DOC-20

2023-01-28 17:13 UTC, imeyer approved these changes
LGTM! Like, realllly looks good!

2023-01-30 16:09 UTC, glittershark requested changes

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +A unique identifier for the ReadySet deployment.
do we want to define what a "readyset deployment" is and why it matters here?

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +TODO
should this be done here?

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +Print help information.
maybe this should go first?

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +        Also, `--log-level` can be set to a comma-separated list of directives for debugging during development. For the directive syntax, see the [logging library docs](https://docs.rs/tracing-subsc
maybe instead of "logging library" we could explicitly say "docs for the tracing library", to *potentially* piggy-back on existing knowledge some users might have for that library (and also give credit the library itself)

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +This memory limit accounts for all memory use, including partial materializations (i.e., queries for which ReadySet stores only part of the result set), full materializations (i.e., queries for which
is the plan to eventually have a "partial vs full materialization" page to link to here?

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +Do not run reader nodes on this Server. Reader nodes are the part of the dataflow graph that serve cached results for a query.
I don't think the word "Server" (vs just "instance") is necessary here - also, why's it capitalized?

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +Output RaedySet metrics.
```suggestion
Output ReadySet metrics.
```

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +Output Prometheus metrics.
probably for later, but we should document that this is exposed via an HTTP endpoint listening at `--metrics-address`

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +#### `--noria-metrics`
hmm, this should probably be hidden tbh

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +Run only reader nodes on this Server. Reader nodes are the part of the dataflow graph that serve cached results for a query.
same comment here re "Server" terminology

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +This option accepts a comma separated list of `<schema>.<table>` for Postgres and `<database>.<table>` for MySQL.
we also support `schema.*` for all tables in a schema

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +By default, ReadySet attempts to snapshot and replicate all tables in the database specified in [`--upstream-db-url`](#-upstream-db-url). However, if the queries you want to cache access only specifi
we *shouldn't* need to avoid snapshotting tables due to containing unsupported data types - if that actually happens now that should hopefully be considered a bug - and then removing that table would really just be a workaround for that bug.

cc @lukoktonos on whether or not that bugfix can be considered landed enough to remove that language here

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +Path to the PEM or DER certificate of the root that the upstream database connection will trust.
I think:

```suggestion
Path to the PEM or DER root certificate that the upstream database connection will trust.
```

2023-01-30 16:09 UTC, glittershark commented on docs/reference/cli/readyset-server.md
> +    By default, ReadySet attempts to snapshot and replicate all tables in specified. However, if the queries you want to cache access only specific tables, or if some tables can't be snapshotted/repl
is this intended to be here? looks duplicated from the `--replication-tables` option

2023-01-30 17:20 UTC, jseldess reviewed
Thanks for the review, @glittershark! Made some changes and left some follow-up questions for you.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +TODO
Yeah, this isn't the right long-term approach. Eventually, I'll create a custom template for this specific style of page: https://readysettech.atlassian.net/browse/DOC-108. For now, though, I can live with this.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Print help information.
I'm listing the options in alphabetical order, but I did include `--help` in the **Usage** section at the top.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +        Also, `--log-level` can be set to a comma-separated list of directives for debugging during development. For the directive syntax, see the [logging library docs](https://docs.rs/tracing-subsc
Done.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +This memory limit accounts for all memory use, including partial materializations (i.e., queries for which ReadySet stores only part of the result set), full materializations (i.e., queries for which
Definitely. For now, I was hoping to explain these terms in a very basic way so as to help users understand the related options.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Do not run reader nodes on this Server. Reader nodes are the part of the dataflow graph that serve cached results for a query.
Changed to "instance". 

But in terms of capitalization: I've been capitalizing "ReadySet Server" and "ReadySet Adapter". But I would also be ok lower-casing server and adapter, if you prefer. I agree that "Server" and "Adapter" on their own look strange.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +#### `--noria-metrics`
Ah, ok. I asked about this in Slack and haven't received a response: https://readyset-workspace.slack.com/archives/C03K0F6FQT1/p1674853880475199. 

I can open an issue to hide `--noria-metrics`. Can you say why, though?

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Output RaedySet metrics.
Done.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Output Prometheus metrics.
Yeah, I was confused about this. `readyset-server` doesn't seem to accept `--metrics-address`, at least that option isn't in the help. Do you know what's up there?

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Run only reader nodes on this Server. Reader nodes are the part of the dataflow graph that serve cached results for a query.
Done.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +By default, ReadySet attempts to snapshot and replicate all tables in the database specified in [`--upstream-db-url`](#-upstream-db-url). However, if the queries you want to cache access only specifi
Good point, Griffin. I can remove that use case, if @lukoktonos agrees.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +This option accepts a comma separated list of `<schema>.<table>` for Postgres and `<database>.<table>` for MySQL.
Done.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Path to the PEM or DER certificate of the root that the upstream database connection will trust.
Done.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +    By default, ReadySet attempts to snapshot and replicate all tables in specified. However, if the queries you want to cache access only specific tables, or if some tables can't be snapshotted/repl
Intentional. We mention that this url contains the db to snapshot/replication, so it seem important to cross-reference the way to reduce that scope.

2023-01-30 17:20 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +A unique identifier for the ReadySet deployment.
Hmm, what did you have in mind. The overall context is stated a few times (standalone vs. distributed).

2023-02-02 21:54 UTC, lukoktonos requested changes

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +In this step, you'll configure your database so that ReadySet can consume the database's replication stream, which ReadySet uses to keep its cache up-to-date as the database changes. In Postgres, the
I think this comment is mixing up 2 different concepts. Both MySQL and Postgres use a method for journaling or writing-ahead changes--MySQL calls it the binary log (linked here) and Postgres calls it the WAL or write-ahead log (https://www.postgresql.org/docs/9.1/wal-intro.html)

The process of consuming or listening to entries in those logs is called replication, and both MySQL and Postgres have a couple different flavors of that. For Postgres, we use logical replication (linked) to listen to the logged changes. In MySQL, the comparable link may be to this page: https://dev.mysql.com/doc/refman/5.7/en/replication.html

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +            If replication is still not enabled, [reboot the database](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RebootInstance.html).
In my experience I've always had to do this, so it may make sense to just be a step rather than a tip.

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +    1. In RDS MySQL, the [binary log](https://dev.mysql.com/doc/refman/5.7/en/binary-log.html) is enabled only when automated backups are also enabled. If you didn't enable automated backups when cre
The binary log is always used by mysql to make changes atomic, so the wording here would be more precise to say it's not available to replicate from unless automated backups are also enabled.

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +            If replication is still not enabled, [reboot the database](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RebootInstance.html).
Havent played with RDS mysql yet, but the same reboot comment may apply here.

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +    - **Region:** ReadySet consumes your database's replication stream, so launch the instance is the same region as your database for optimal performance.
```suggestion
    - **Region:** ReadySet consumes your database's replication stream, so launch the instance in the same region as your database for optimal performance.
```

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +      curl -sL https://github.com/readysettech/readyset/releases/download/beta-2023-01-18/readyset-beta-2023-01-18.x86_64.tar.gz \
We can almost get away with using https://github.com/readysettech/readyset/releases/latest here, but the file name will be different. I wonder if we shouldn't use the release version in the tar.gz name so we could get away with it.

2023-02-02 21:54 UTC, lukoktonos commented on docs/reference/cli/readyset-server.md
> +By default, ReadySet attempts to snapshot and replicate all tables in the database specified in [`--upstream-db-url`](#-upstream-db-url). However, if the queries you want to cache access only specifi
Yeah we should remove that wording here--internally, we do end up not snapshotting those tables, but we handle that automatically and don't rely on the user to filter them out.

It may also be good to add a sentence here to the effect of "Filtering out tables you know will not be used in caches will speed up the snapshotting process."

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +TBD
Should this match the cloud page?

![image](https://user-images.githubusercontent.com/14879344/216457252-a9826a4c-b8c0-469b-adc0-f097b223806a.png)

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +        cat logs/readyset.log | grep 'taking database snapshot'
nit: this is a [useless use of cat](https://blog.sanctum.geek.nz/useless-use-of-cat/)

2023-02-02 21:54 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +        - **Not Replicated:** The table has not been snapshotted by ReadySet. This can be because the table contains [unsupported data types](../reference/sql-support.md#data-types) or has been inten
We may want to expand on the "Unsupported types" and be more general here: "This may be because ReadySet encountered an error snapshotting (such as an unsupported data type) or..."

2023-02-03 18:38 UTC, jseldess reviewed
TFTR, @lukoktonos! Let me know if you have any remaining concerns.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +In this step, you'll configure your database so that ReadySet can consume the database's replication stream, which ReadySet uses to keep its cache up-to-date as the database changes. In Postgres, the
I think this calls for a distinct conceptual page rather than explaining the details here and in other tutorials: https://readysettech.atlassian.net/browse/DOC-111. For now, I'll simplify.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +    1. In RDS MySQL, the [binary log](https://dev.mysql.com/doc/refman/5.7/en/binary-log.html) is enabled only when automated backups are also enabled. If you didn't enable automated backups when cre
Simplified things to just refer to replication, for now.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +    - **Region:** ReadySet consumes your database's replication stream, so launch the instance is the same region as your database for optimal performance.
Done.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +        - **Not Replicated:** The table has not been snapshotted by ReadySet. This can be because the table contains [unsupported data types](../reference/sql-support.md#data-types) or has been inten
Done.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +        cat logs/readyset.log | grep 'taking database snapshot'
Thanks for catching this. Done, here and elsewhere.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +TBD
I don't think we want the same guidance here, no. Core users don't get a private Slack channel. I'll work on these next steps next.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +      curl -sL https://github.com/readysettech/readyset/releases/download/beta-2023-01-18/readyset-beta-2023-01-18.x86_64.tar.gz \
That does sound convenient, but it's also somehow nice to have the version in the filename, for clarify. Otherwise, you always have to run `readyset --version` to figure out which version you might have downloaded.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +            If replication is still not enabled, [reboot the database](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RebootInstance.html).
I'd prefer to leave this, since you "apply immediately" for the parameter group. I think that does sometimes work.

2023-02-03 18:38 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +            If replication is still not enabled, [reboot the database](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RebootInstance.html).
I prefer to leave this.

2023-02-03 21:46 UTC, lukoktonos commented on docs/guides/deploy-readyset-binary.md
> +    1. In RDS MySQL, the [replication](https://dev.mysql.com/doc/refman/5.7/en/replication.html) is enabled only when automated backups are also enabled. If you didn't enable automated backups when c
```suggestion
    1. In RDS MySQL, [replication](https://dev.mysql.com/doc/refman/5.7/en/replication.html) is enabled only when automated backups are also enabled. If you didn't enable automated backups when creating your database instance, [enable automated backups](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html#USER_WorkingWithAutomatedBackups.Enabling) now.
```

2023-02-03 21:47 UTC, lukoktonos approved these changes
nice!

2023-02-03 21:48 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +By default, ReadySet attempts to snapshot and replicate all tables in the database specified in [`--upstream-db-url`](#-upstream-db-url). However, if the queries you want to cache access only specifi
Done.

2023-02-03 21:49 UTC, jseldess commented on docs/guides/deploy-readyset-binary.md
> +    1. In RDS MySQL, the [replication](https://dev.mysql.com/doc/refman/5.7/en/replication.html) is enabled only when automated backups are also enabled. If you didn't enable automated backups when c
Done.

2023-02-03 21:55 UTC, merged

2023-02-03 21:56 UTC, greg-mckeon commented on docs/guides/deploy-readyset-kubernetes.md
> +    - Make sure [row-level security](https://www.postgresql.org/docs/current/ddl-rowsecurity.html) is disabled. ReadySet does not current support row-level security.
nit: currently

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/index.md
> +    The ReadySet CLI is relevant only for users running ReadySet themselves. Users on ReadySet Cloud get a fully-managed deployment of ReadySet and do not need to run `readyset` commands.
this is true, but they will still need to connect and issue CREATE CACHE commands.

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/readyset-server.md
> +Disable verification of SSL certificates supplied by the upstream database (Postgres only, ignored for MySQL).
this affects both the replication connection and any upstream connections used for issuing queries, right?

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/readyset-server.md
> +    Consider passing this option when ReadySet Adapters use the `"inrequestpath"` or `"async"` [query caching mode](readyset.md#-query-caching). In both cases, queries are cached by ReadySet automati
nit: i would say "exhaust memory" instead of "run into memory issues".

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/readyset-server.md
> +- `ERROR`: Used for hazardous situations that require special handling, where normal operation cannot proceed as expected.
This is not exactly true today - many of our errors are actually fine.  I don't think we should change the docs, we should change the server, but FYI

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/readyset-server.md
> +Path to the PEM or DER root certificate that the upstream database connection will trust.
We will also use the system root store without this being set.

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/readyset.md
> +#### `--non-blocking-reads`
I'm having a hard time imagining when we would want to set this to False.  Maybe we should leave undocumented?

2023-02-03 21:56 UTC, greg-mckeon commented on docs/reference/cli/readyset.md
> +    This can be set as high as the number of tables you want ReadySet to snapshot/replicate. However, note that the more connections you use for snapshotting/replication, the higher the load on your
Also, the more memory you'll use during snapshotting.  You can OOM your box like this 🙃

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/index.md
> +    The ReadySet CLI is relevant only for users running ReadySet themselves. Users on ReadySet Cloud get a fully-managed deployment of ReadySet and do not need to run `readyset` commands.
By "CLI", we're talking about the `readyset` and `readyset-server` commands. `CREATE CACHE` is SQL and doesn't require these commands.

2023-02-06 16:52 UTC, jseldess commented on docs/guides/deploy-readyset-kubernetes.md
> +    - Make sure [row-level security](https://www.postgresql.org/docs/current/ddl-rowsecurity.html) is disabled. ReadySet does not current support row-level security.
Fixed.

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Disable verification of SSL certificates supplied by the upstream database (Postgres only, ignored for MySQL).
Sounds right, but I'm not sure. Asking around.

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +    Consider passing this option when ReadySet Adapters use the `"inrequestpath"` or `"async"` [query caching mode](readyset.md#-query-caching). In both cases, queries are cached by ReadySet automati
Done.

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +- `ERROR`: Used for hazardous situations that require special handling, where normal operation cannot proceed as expected.
Good to know. Started a thread on this: https://readyset-workspace.slack.com/archives/C03K0F6FQT1/p1675700980971489.

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Path to the PEM or DER root certificate that the upstream database connection will trust.
Added that as default. Thanks.

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/readyset.md
> +#### `--non-blocking-reads`
Are you saying that we want this behavior by default? We don't want to require users to pass the flag? If so, perhaps we should change this to `--blocking-reads` and require users to pass this when they *don't* want us to proxy queries for cache misses? @glittershark, thoughts?

2023-02-06 16:52 UTC, jseldess commented on docs/reference/cli/readyset.md
> +    This can be set as high as the number of tables you want ReadySet to snapshot/replicate. However, note that the more connections you use for snapshotting/replication, the higher the load on your
Done.

2023-02-06 16:59 UTC, jseldess commented on docs/reference/cli/readyset-server.md
> +Disable verification of SSL certificates supplied by the upstream database (Postgres only, ignored for MySQL).
Confirmed.